apiVersion: v1
kind: Service
metadata:
  name: lanchonete-api-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: LoadBalancer
  selector:
    app: lanchonete-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080