apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-db-volume-claim
  labels:
    app: orders-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi