apiVersion: v1
kind: PersistentVolume
metadata:
  name: orders-db-volume
  labels:
    app: orders-db
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql