apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-api-config
  labels:
    app: orders-api
data:
  API_PORT: "31200"
  PORT_SERVER: "8080"
  MONOLITH_PORT: "8080"
  MONOLITH_HOST: "lanchonete-api-service"

  PRODUCTS_SERVICE_HOST: lanchonete-api-service
  PRODUCTS_SERVICE_PORT: "31200"
  CUSTOMERS_SERVICE_HOST: lanchonete-api-service
  CUSTOMERS_SERVICE_PORT: "31200"

  POSTGRES_HOST: orders-db
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "orders-database"
  POSTGRES_USER: "postgres"
