apiVersion: v1
kind: Service
metadata:
  name: orders-api-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: LoadBalancer
  selector:
    app: orders-api
    type: microservice
  ports:
    - protocol: TCP
      port: 31201
      targetPort: 8080