apiVersion: v1
kind: PersistentVolume
metadata:
  name: lanchonete-db-volume
  labels:
    app: lanchonete-db
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql